setwd("D:/Date/g20_VPA")
library(ape)
library(spdep)
library(vegan)
library(ade4)
library(packfor)
library(packfor)
library(spacemakeR)
library(AEM)
library(PCNM)
mite<-read.table("nSCS_g20.txt",header=T,row.name=1)
mite.h<- decostand(mite, "hellinger")
env<-read.csv("nscs_env.csv",header=T,row.name=1)
mite.xy<-read.csv("mitexy.csv",header=T,row.name=1)
mite.xy.c <-scale(mite.xy, center=TRUE, scale=FALSE)
xy.d1 <- dist(mite.xy)
mite.PCNM.auto <-PCNM(xy.d1)
summary(mite.PCNM.auto)
mite.PCNM.auto$expected_Moran
mite.PCNM.auto$Moran_I
(select <-which(mite.PCNM.auto$Moran_I$Positive==TRUE))
length(select)
mite.PCNM.pos <-as.data.frame(mite.PCNM.auto$vectors)[,select] 
write.csv(as.matrix(mite.PCNM.pos), 'mite_PCNM_pos.csv', quote = F)
mite.varpart<-varpart(mite.h,env,mite.BC15,mite.xy)
View(mite.varpart)
par(mfrow=c(1,2))
showvarparts(3)
plot(mite.varpart,digits=2)

